version: "3"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/back

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./frontend:/front
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /front

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: