version: "3"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend/pract:/var/www
    working_dir: /var/www

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend/pract:/var/www
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: